-- MySQL Script generated by MySQL Workbench
-- 10/10/17 09:56:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema educacionculturaturismosb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `educacionculturaturismosb` ;

-- -----------------------------------------------------
-- Schema educacionculturaturismosb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `educacionculturaturismosb` DEFAULT CHARACTER SET utf8 ;
USE `educacionculturaturismosb` ;

-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`tipoactividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`tipoactividad` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`tipoactividad` (
  `idtipoactividad` INT(11) NOT NULL AUTO_INCREMENT,
  `nomtipoactividad` VARCHAR(250) NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipoactividad`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`actividad` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`actividad` (
  `idactividad` INT(11) NOT NULL AUTO_INCREMENT,
  `nomactividad` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `imagen` VARCHAR(70) NULL DEFAULT NULL,
  `objetivo` VARCHAR(250) NULL DEFAULT NULL,
  `idtipoactividad` INT(11) NOT NULL,
  PRIMARY KEY (`idactividad`),
  INDEX `fk_actividad_tipoactividad_idx` (`idtipoactividad` ASC),
  CONSTRAINT `fk_actividad_tipoactividad`
    FOREIGN KEY (`idtipoactividad`)
    REFERENCES `educacionculturaturismosb`.`tipoactividad` (`idtipoactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`sede` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`sede` (
  `idsede` INT(11) NOT NULL AUTO_INCREMENT,
  `nombresede` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idsede`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`ambiente` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`ambiente` (
  `idambiente` INT(11) NOT NULL AUTO_INCREMENT,
  `idsede` INT(11) NOT NULL,
  `capacidad` INT(11) NULL DEFAULT NULL,
  `nombreambiente` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`idambiente`),
  INDEX `fk_ambiente_sede1_idx` (`idsede` ASC),
  CONSTRAINT `fk_ambiente_sede1`
    FOREIGN KEY (`idsede`)
    REFERENCES `educacionculturaturismosb`.`sede` (`idsede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`empleado` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`empleado` (
  `idempleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellipaterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellimaterno` VARCHAR(100) NULL DEFAULT NULL,
  `dni` INT(11) NULL DEFAULT NULL,
  `telefono` INT(11) NULL DEFAULT NULL,
  `celular` INT(11) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`periodo` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`periodo` (
  `idperiodo` INT(11) NOT NULL AUTO_INCREMENT,
  `nomperiodo` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`idperiodo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`planificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`planificacion` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`planificacion` (
  `idplanificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `fechacreacion` DATE NULL DEFAULT NULL,
  `fechaplanificacion` DATE NULL DEFAULT NULL,
  `fecharechazo` DATE NULL DEFAULT NULL,
  `fechaaprobacion` DATE NULL DEFAULT NULL,
  `idperiodo` INT(11) NOT NULL,
  `idactividad` INT(11) NOT NULL,
  `fechaanulacion` DATE NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `fechaejecucion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idplanificacion`),
  INDEX `fk_planificacion_periodo1_idx` (`idperiodo` ASC),
  INDEX `fk_planificacion_actividad1_idx` (`idactividad` ASC),
  CONSTRAINT `fk_planificacion_actividad1`
    FOREIGN KEY (`idactividad`)
    REFERENCES `educacionculturaturismosb`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planificacion_periodo1`
    FOREIGN KEY (`idperiodo`)
    REFERENCES `educacionculturaturismosb`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 147
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`horario` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`horario` (
  `idhorario` INT(11) NOT NULL AUTO_INCREMENT,
  `idambiente` INT(11) NOT NULL,
  `fechainicio` DATE NULL DEFAULT NULL,
  `fechafin` DATE NULL DEFAULT NULL,
  `edadmin` INT(11) NULL DEFAULT NULL,
  `edadmax` INT(11) NULL DEFAULT NULL,
  `cantsesion` INT(11) NULL DEFAULT NULL,
  `horassesion` INT(11) NULL DEFAULT NULL,
  `vacantemin` INT(11) NULL DEFAULT NULL,
  `vacantemax` INT(11) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `idplanificacion` INT(11) NOT NULL,
  PRIMARY KEY (`idhorario`),
  INDEX `fk_horario_ambiente1_idx` (`idambiente` ASC),
  INDEX `fk_horario_planificacion1_idx` (`idplanificacion` ASC),
  CONSTRAINT `fk_horario_ambiente1`
    FOREIGN KEY (`idambiente`)
    REFERENCES `educacionculturaturismosb`.`ambiente` (`idambiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_planificacion1`
    FOREIGN KEY (`idplanificacion`)
    REFERENCES `educacionculturaturismosb`.`planificacion` (`idplanificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`cronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`cronograma` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`cronograma` (
  `idcronograma` INT(11) NOT NULL AUTO_INCREMENT,
  `idhorario` INT(11) NOT NULL,
  `tarea` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `fechainicio` DATE NULL DEFAULT NULL,
  `fechafin` DATE NULL DEFAULT NULL,
  `fechaejecucion` DATE NULL DEFAULT NULL,
  `idempleado` INT(11) NOT NULL,
  PRIMARY KEY (`idcronograma`),
  INDEX `fk_cronograma_horario1_idx` (`idhorario` ASC),
  INDEX `fk_cronograma_empleado1_idx` (`idempleado` ASC),
  CONSTRAINT `fk_cronograma_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `educacionculturaturismosb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cronograma_horario1`
    FOREIGN KEY (`idhorario`)
    REFERENCES `educacionculturaturismosb`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`rol` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`rol` (
  `idrol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrerol` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`detalle_empleado_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`detalle_empleado_rol` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`detalle_empleado_rol` (
  `idempleado` INT(11) NOT NULL,
  `idrol` INT(11) NOT NULL,
  PRIMARY KEY (`idempleado`, `idrol`),
  INDEX `fk_empleado_has_rol_rol1_idx` (`idrol` ASC),
  INDEX `fk_empleado_has_rol_empleado1_idx` (`idempleado` ASC),
  CONSTRAINT `fk_empleado_has_rol_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `educacionculturaturismosb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_has_rol_rol1`
    FOREIGN KEY (`idrol`)
    REFERENCES `educacionculturaturismosb`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`detalle_horario_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`detalle_horario_empleado` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`detalle_horario_empleado` (
  `idhorario` INT(11) NOT NULL,
  `idempleado` INT(11) NOT NULL,
  PRIMARY KEY (`idhorario`, `idempleado`),
  INDEX `fk_horario_has_empleado_empleado1_idx` (`idempleado` ASC),
  INDEX `fk_horario_has_empleado_horario1_idx` (`idhorario` ASC),
  CONSTRAINT `fk_horario_has_empleado_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `educacionculturaturismosb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_has_empleado_horario1`
    FOREIGN KEY (`idhorario`)
    REFERENCES `educacionculturaturismosb`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`material` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`material` (
  `idmaterial` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad_disponible` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idmaterial`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`detalle_horario_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`detalle_horario_material` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`detalle_horario_material` (
  `idhorario` INT(11) NOT NULL,
  `idmaterial` INT(11) NOT NULL,
  `cantidad_usar` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idhorario`, `idmaterial`),
  INDEX `fk_horario_has_material_material1_idx` (`idmaterial` ASC),
  INDEX `fk_horario_has_material_horario1_idx` (`idhorario` ASC),
  CONSTRAINT `fk_horario_has_material_horario1`
    FOREIGN KEY (`idhorario`)
    REFERENCES `educacionculturaturismosb`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_has_material_material1`
    FOREIGN KEY (`idmaterial`)
    REFERENCES `educacionculturaturismosb`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`motivorechazo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`motivorechazo` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`motivorechazo` (
  `idmotivo` INT(11) NOT NULL,
  `descmotivo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmotivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`detalle_rechazo_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`detalle_rechazo_plan` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`detalle_rechazo_plan` (
  `idrechazoplan` INT(11) NOT NULL,
  `idmotivo` INT(11) NOT NULL,
  `idplanificacion` INT(11) NOT NULL,
  `fecharechazo` DATE NULL DEFAULT NULL,
  `observacion` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad_usar` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idrechazoplan`),
  INDEX `fk_planificacion_has_motivo_motivo1_idx` (`idmotivo` ASC),
  INDEX `fk_planificacion_has_motivo_planificacion1_idx` (`idplanificacion` ASC),
  CONSTRAINT `fk_planificacion_has_motivo_motivo1`
    FOREIGN KEY (`idmotivo`)
    REFERENCES `educacionculturaturismosb`.`motivorechazo` (`idmotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planificacion_has_motivo_planificacion1`
    FOREIGN KEY (`idplanificacion`)
    REFERENCES `educacionculturaturismosb`.`planificacion` (`idplanificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`planpublicitario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`planpublicitario` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`planpublicitario` (
  `idplanpublicitario` INT(11) NOT NULL AUTO_INCREMENT,
  `archivoruta` VARCHAR(60) NULL DEFAULT NULL,
  `descripcion` VARCHAR(60) NULL DEFAULT NULL,
  `idplanificacion` INT(11) NOT NULL,
  PRIMARY KEY (`idplanpublicitario`),
  INDEX `fk_planpublicitario_planificacion1_idx` (`idplanificacion` ASC),
  CONSTRAINT `fk_planpublicitario_planificacion1`
    FOREIGN KEY (`idplanificacion`)
    REFERENCES `educacionculturaturismosb`.`planificacion` (`idplanificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `educacionculturaturismosb`.`dia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educacionculturaturismosb`.`dia` ;

CREATE TABLE IF NOT EXISTS `educacionculturaturismosb`.`dia` (
  `iddia` INT NOT NULL AUTO_INCREMENT,
  `idhorario` INT(11) NOT NULL,
  `horainicio` VARCHAR(45) NULL,
  `horafin` VARCHAR(45) NULL,
  `dia` VARCHAR(45) NULL,
  PRIMARY KEY (`iddia`, `idhorario`),
  INDEX `fk_dia_horario1_idx` (`idhorario` ASC),
  CONSTRAINT `fk_dia_horario1`
    FOREIGN KEY (`idhorario`)
    REFERENCES `educacionculturaturismosb`.`horario` (`idhorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `educacionculturaturismosb` ;

-- -----------------------------------------------------
-- procedure ConsultarCronograma
-- -----------------------------------------------------

USE `educacionculturaturismosb`;
DROP procedure IF EXISTS `educacionculturaturismosb`.`ConsultarCronograma`;

DELIMITER $$
USE `educacionculturaturismosb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ConsultarCronograma`(IN idHorario int(11), IN idCronograma int(11))
BEGIN

	DECLARE V_WHERE VARCHAR(50) default '';

	IF(idCronograma>0) THEN
		SET V_WHERE = CONCAT(' AND idCronograma=', idCronograma);
    END IF;
    
    
	/*SET @sql = CONCAT('SELECT COUNT(*) FROM ', tab_name);*/
    SET @sql = CONCAT('SELECT TB1.idCronograma,TB1.tarea,TB1.descripcion,TB2.nombre,TB2.apellipaterno,
					   TB1.fechaInicio,TB1.fechaFin
                       FROM educacionculturaturismosb.cronograma TB1
					   LEFT JOIN educacionculturaturismosb.empleado TB2
                       ON TB1.codEmpleado = TB2.codEmpleado
					   WHERE idHorario =',idHorario,V_WHERE);
	PREPARE stmt FROM @sql;
	EXECUTE stmt;
	DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ConsultarHorario
-- -----------------------------------------------------

USE `educacionculturaturismosb`;
DROP procedure IF EXISTS `educacionculturaturismosb`.`ConsultarHorario`;

DELIMITER $$
USE `educacionculturaturismosb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ConsultarHorario`()
BEGIN
  
  		SELECT h.idhorario as idhorario,
  		s.nombresede as nombresede,
  		a.nombreambiente as nombreambiente,
  		concat(h.edadmin," aÃ±o(s) a ",h.edadmax, " aÃ±o(s)") as dirigido,
  		h.cantsesion as cantsesion,
  		h.horassesion as horassesion,
  		h.vacantemin as vacantemin,
  		h.vacantemax as vacantemax,
  		h.fechainicio as fechainicio,
  		h.fechafin as  fechafin,
  		h.precio as precio
  
  
  		from
  		horario h inner join ambiente a on h.idambiente=a.idambiente
  		 inner join sede s on a.idsede = s.idsede
  		;
  	END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtenerPlanificacionXPeriodoXActividad
-- -----------------------------------------------------

USE `educacionculturaturismosb`;
DROP procedure IF EXISTS `educacionculturaturismosb`.`obtenerPlanificacionXPeriodoXActividad`;

DELIMITER $$
USE `educacionculturaturismosb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `obtenerPlanificacionXPeriodoXActividad`(IN Val_idperiodo INT, IN Val_estado INT)
    DETERMINISTIC
BEGIN
			IF (Val_idperiodo !=0) AND (Val_estado !=0)  THEN
			
				Select pl.idplanificacion as idplanificacion,
					p.nomperiodo as nomperiodo,
					pl.fechacreacion as fechacreacion,
					pl.fechaplanificacion as fechaplanificacion,
					pl.fechaaprobacion as fechaaprobacion,
					pl.fecharechazo as fecharechazo,
					pl.fechaanulacion as fechaanulacion,
					pl.fechaejecucion as fechaejecucion,
					a.nomactividad as nomactividad,
					ta.nomtipoactividad as nomtipoactividad, 
					case pl.estado 
					when 1 then "Pendiente" 
					when 2 then "Planificado"
					when 3 then "Aprobado"
					when 4 then "Rechazado"
					when 5 then "Ejecutado"
					when 6 then "Anulado"
					end  as estado
					
					from planificacion pl inner join periodo p on pl.idperiodo=p.idperiodo
					inner join actividad a on pl.idactividad=a.idactividad
					inner join tipoactividad ta on a.idtipoactividad = ta.idtipoactividad
					
					 WHERE p.idperiodo=Val_idperiodo and pl.estado=Val_estado;
			ELSE 
				  
					Select pl.idplanificacion as idplanificacion,
					p.nomperiodo as nomperiodo,
					pl.fechacreacion as fechacreacion,
					pl.fechaplanificacion as fechaplanificacion,
					pl.fechaaprobacion as fechaaprobacion,
					pl.fecharechazo as fecharechazo,
					pl.fechaanulacion as fechaanulacion,
					pl.fechaejecucion as fechaejecucion,
					a.nomactividad as nomactividad,
					ta.nomtipoactividad as nomtipoactividad, 
					case pl.estado 
					when 1 then "Pendiente" 
					when 2 then "Planificado"
					when 3 then "Aprobado"
					when 4 then "Rechazado"
					when 5 then "Ejecutado"
					when 6 then "Anulado"
					end  as estado
					
					from planificacion pl inner join periodo p on pl.idperiodo=p.idperiodo
					inner join actividad a on pl.idactividad=a.idactividad
					inner join tipoactividad ta on a.idtipoactividad = ta.idtipoactividad;
					
			END IF;
        END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure validarActividadPorPeriodo
-- -----------------------------------------------------

USE `educacionculturaturismosb`;
DROP procedure IF EXISTS `educacionculturaturismosb`.`validarActividadPorPeriodo`;

DELIMITER $$
USE `educacionculturaturismosb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `validarActividadPorPeriodo`(IN Val_idperiodo INT, IN Val_idtipoactividad INT, IN Val_idactividad INT)
    DETERMINISTIC
BEGIN
			Select count(pl.idplanificacion) as flagactividadperiodo
			from planificacion pl inner join periodo p on pl.idperiodo=p.idperiodo and p.idperiodo=Val_idperiodo
			inner join actividad a on pl.idactividad=a.idactividad and a.idactividad=Val_idactividad
			inner join tipoactividad ta on a.idtipoactividad = ta.idtipoactividad and ta.idtipoactividad=Val_idtipoactividad;
			 
        END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
